// Code generated by protoc-gen-go. DO NOT EDIT.
// source: AreaType.proto

package proto_dic

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AreaType int32

const (
	AreaType_noType    AreaType = 140000
	AreaType_point     AreaType = 140001
	AreaType_circle    AreaType = 140002
	AreaType_rectangle AreaType = 140003
	AreaType_polygon   AreaType = 140004
	AreaType_route     AreaType = 140005
	AreaType_segment   AreaType = 140006
)

var AreaType_name = map[int32]string{
	140000: "noType",
	140001: "point",
	140002: "circle",
	140003: "rectangle",
	140004: "polygon",
	140005: "route",
	140006: "segment",
}
var AreaType_value = map[string]int32{
	"noType":    140000,
	"point":     140001,
	"circle":    140002,
	"rectangle": 140003,
	"polygon":   140004,
	"route":     140005,
	"segment":   140006,
}

func (x AreaType) Enum() *AreaType {
	p := new(AreaType)
	*p = x
	return p
}
func (x AreaType) String() string {
	return proto.EnumName(AreaType_name, int32(x))
}
func (x *AreaType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AreaType_value, data, "AreaType")
	if err != nil {
		return err
	}
	*x = AreaType(value)
	return nil
}
func (AreaType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_AreaType_195a13894a2c0345, []int{0}
}

func init() {
	proto.RegisterEnum("proto_dic.AreaType", AreaType_name, AreaType_value)
}

func init() { proto.RegisterFile("AreaType.proto", fileDescriptor_AreaType_195a13894a2c0345) }

var fileDescriptor_AreaType_195a13894a2c0345 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xcb, 0x4b, 0xaa, 0x02, 0x41,
	0x0c, 0x85, 0xe1, 0xd1, 0xbd, 0xa6, 0xe3, 0x2b, 0xd4, 0x32, 0x1c, 0xb8, 0x07, 0xf7, 0xe0, 0x5c,
	0x9a, 0x32, 0x14, 0x05, 0x65, 0xa5, 0x88, 0x71, 0xd0, 0x0b, 0xcc, 0x3e, 0x7c, 0xaf, 0x43, 0xda,
	0xc6, 0xd1, 0x39, 0xf0, 0xf1, 0xe3, 0x6a, 0xa7, 0xdc, 0xef, 0x87, 0xc6, 0xdb, 0xa6, 0x62, 0x12,
	0xba, 0xef, 0x1c, 0x8e, 0x39, 0x6e, 0x04, 0xe1, 0x87, 0x61, 0x81, 0xff, 0x55, 0xc6, 0x47, 0x57,
	0x87, 0x30, 0xc7, 0xbf, 0x26, 0xb9, 0x1a, 0xdd, 0x1c, 0x46, 0x8a, 0x59, 0x63, 0x61, 0xba, 0x3b,
	0x84, 0x35, 0x76, 0xca, 0xd1, 0xfa, 0x9a, 0x0a, 0xd3, 0xc3, 0x21, 0x2c, 0x71, 0xd6, 0xa4, 0x0c,
	0x49, 0x2a, 0x3d, 0xa7, 0x54, 0xe5, 0x62, 0x4c, 0xaf, 0xc9, 0xce, 0x9c, 0x4e, 0x5c, 0x8d, 0xde,
	0x0e, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x47, 0x4b, 0x4d, 0x13, 0x8c, 0x00, 0x00, 0x00,
}
