// Code generated by protoc-gen-go. DO NOT EDIT.
// source: LocationData.proto

package proto_dic

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignalStatus int32

const (
	SignalStatus_nearLight         SignalStatus = 1
	SignalStatus_farLight          SignalStatus = 2
	SignalStatus_rightTurningLight SignalStatus = 4
	SignalStatus_leftTurningLight  SignalStatus = 8
	SignalStatus_braking           SignalStatus = 16
	SignalStatus_reverse           SignalStatus = 32
	SignalStatus_fogLight          SignalStatus = 64
	SignalStatus_markerLight       SignalStatus = 128
	SignalStatus_speaker           SignalStatus = 256
	SignalStatus_airConditioning   SignalStatus = 512
	SignalStatus_neutral           SignalStatus = 1024
	SignalStatus_retarder          SignalStatus = 2048
	SignalStatus_absWorking        SignalStatus = 4096
	SignalStatus_heaterWorking     SignalStatus = 8192
	SignalStatus_clutchStatus      SignalStatus = 16384
)

var SignalStatus_name = map[int32]string{
	1:     "nearLight",
	2:     "farLight",
	4:     "rightTurningLight",
	8:     "leftTurningLight",
	16:    "braking",
	32:    "reverse",
	64:    "fogLight",
	128:   "markerLight",
	256:   "speaker",
	512:   "airConditioning",
	1024:  "neutral",
	2048:  "retarder",
	4096:  "absWorking",
	8192:  "heaterWorking",
	16384: "clutchStatus",
}
var SignalStatus_value = map[string]int32{
	"nearLight":         1,
	"farLight":          2,
	"rightTurningLight": 4,
	"leftTurningLight":  8,
	"braking":           16,
	"reverse":           32,
	"fogLight":          64,
	"markerLight":       128,
	"speaker":           256,
	"airConditioning":   512,
	"neutral":           1024,
	"retarder":          2048,
	"absWorking":        4096,
	"heaterWorking":     8192,
	"clutchStatus":      16384,
}

func (x SignalStatus) Enum() *SignalStatus {
	p := new(SignalStatus)
	*p = x
	return p
}
func (x SignalStatus) String() string {
	return proto.EnumName(SignalStatus_name, int32(x))
}
func (x *SignalStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SignalStatus_value, data, "SignalStatus")
	if err != nil {
		return err
	}
	*x = SignalStatus(value)
	return nil
}
func (SignalStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_LocationData_ad819f23dcf63e85, []int{0}
}

type IoStauts int32

const (
	IoStauts_deepSleeping IoStauts = 1
	IoStauts_sleeping     IoStauts = 2
)

var IoStauts_name = map[int32]string{
	1: "deepSleeping",
	2: "sleeping",
}
var IoStauts_value = map[string]int32{
	"deepSleeping": 1,
	"sleeping":     2,
}

func (x IoStauts) Enum() *IoStauts {
	p := new(IoStauts)
	*p = x
	return p
}
func (x IoStauts) String() string {
	return proto.EnumName(IoStauts_name, int32(x))
}
func (x *IoStauts) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(IoStauts_value, data, "IoStauts")
	if err != nil {
		return err
	}
	*x = IoStauts(value)
	return nil
}
func (IoStauts) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_LocationData_ad819f23dcf63e85, []int{1}
}

type LocationData struct {
	Alarm                   *int64                     `protobuf:"varint,1,req,name=alarm" json:"alarm,omitempty"`
	Status                  *int64                     `protobuf:"varint,2,req,name=status" json:"status,omitempty"`
	Longitude               *int32                     `protobuf:"varint,3,opt,name=longitude" json:"longitude,omitempty"`
	Latitude                *int32                     `protobuf:"varint,4,opt,name=latitude" json:"latitude,omitempty"`
	OriginalLng             *int32                     `protobuf:"varint,5,opt,name=originalLng" json:"originalLng,omitempty"`
	OriginalLat             *int32                     `protobuf:"varint,6,opt,name=originalLat" json:"originalLat,omitempty"`
	Height                  *int32                     `protobuf:"varint,7,req,name=height" json:"height,omitempty"`
	Speed                   *int32                     `protobuf:"varint,8,req,name=speed" json:"speed,omitempty"`
	Direction               *int32                     `protobuf:"varint,9,req,name=direction" json:"direction,omitempty"`
	GpsDate                 *int64                     `protobuf:"varint,10,req,name=gpsDate" json:"gpsDate,omitempty"`
	Mileage                 *int64                     `protobuf:"varint,11,opt,name=mileage" json:"mileage,omitempty"`
	ReceiveDate             *int64                     `protobuf:"varint,12,req,name=receiveDate" json:"receiveDate,omitempty"`
	IsPatch                 *bool                      `protobuf:"varint,13,req,name=isPatch" json:"isPatch,omitempty"`
	Oil                     *int32                     `protobuf:"varint,14,opt,name=oil" json:"oil,omitempty"`
	RecorderSpeed           *int32                     `protobuf:"varint,15,opt,name=recorderSpeed" json:"recorderSpeed,omitempty"`
	SpeedAddition           []*SpeedAddition           `protobuf:"bytes,16,rep,name=speedAddition" json:"speedAddition,omitempty"`
	AreaAddition            []*AreaAddition            `protobuf:"bytes,17,rep,name=areaAddition" json:"areaAddition,omitempty"`
	RouteAddition           []*RouteAddition           `protobuf:"bytes,18,rep,name=routeAddition" json:"routeAddition,omitempty"`
	TemAlarm                []*TemAddition             `protobuf:"bytes,19,rep,name=temAlarm" json:"temAlarm,omitempty"`
	StarStatus              *int32                     `protobuf:"varint,20,opt,name=starStatus" json:"starStatus,omitempty"`
	StarNumber              *int32                     `protobuf:"varint,21,opt,name=starNumber" json:"starNumber,omitempty"`
	AlarmIdentify           []int32                    `protobuf:"varint,22,rep,name=alarmIdentify" json:"alarmIdentify,omitempty"`
	SignalStatus            *int32                     `protobuf:"varint,23,opt,name=signalStatus" json:"signalStatus,omitempty"`
	IoStatus                *int32                     `protobuf:"varint,24,opt,name=ioStatus" json:"ioStatus,omitempty"`
	AnalogAD0               *int32                     `protobuf:"varint,25,opt,name=analogAD0" json:"analogAD0,omitempty"`
	AnalogAD1               *int32                     `protobuf:"varint,26,opt,name=analogAD1" json:"analogAD1,omitempty"`
	SignalStrength          *int32                     `protobuf:"varint,27,opt,name=signalStrength" json:"signalStrength,omitempty"`
	SatelliteNumber         *int32                     `protobuf:"varint,28,opt,name=satelliteNumber" json:"satelliteNumber,omitempty"`
	IsValid                 *bool                      `protobuf:"varint,29,opt,name=isValid" json:"isValid,omitempty"`
	DefenceAddition         []*KeyPointFenceAddition   `protobuf:"bytes,30,rep,name=defenceAddition" json:"defenceAddition,omitempty"`
	ParkingAddition         []*OvertimeParkingAddition `protobuf:"bytes,31,rep,name=parkingAddition" json:"parkingAddition,omitempty"`
	StatusAddition          *VehicleStatusAddition     `protobuf:"bytes,32,opt,name=statusAddition" json:"statusAddition,omitempty"`
	BreakdownAddition       *VehicleBreakdownAddition  `protobuf:"bytes,33,opt,name=breakdownAddition" json:"breakdownAddition,omitempty"`
	AdditionAlarm           []byte                     `protobuf:"bytes,34,opt,name=additionAlarm" json:"additionAlarm,omitempty"`
	AnalysisData            *DrivingBehaviorAnalysis   `protobuf:"bytes,35,opt,name=analysisData" json:"analysisData,omitempty"`
	BatteryPower            *int32                     `protobuf:"varint,36,opt,name=batteryPower" json:"batteryPower,omitempty"`
	ModuleVoltages          []*ModuleVoltage           `protobuf:"bytes,37,rep,name=moduleVoltages" json:"moduleVoltages,omitempty"`
	ElectricVehicle         *int64                     `protobuf:"varint,38,opt,name=electricVehicle" json:"electricVehicle,omitempty"`
	BatteryInfo             *BatteryVehicleInfo        `protobuf:"bytes,39,opt,name=batteryInfo" json:"batteryInfo,omitempty"`
	AlarmFilter             *int64                     `protobuf:"varint,40,opt,name=alarmFilter" json:"alarmFilter,omitempty"`
	StandardMileage         *float32                   `protobuf:"fixed32,42,opt,name=standardMileage" json:"standardMileage,omitempty"`
	StandardFuelCon         *float32                   `protobuf:"fixed32,43,opt,name=standardFuelCon" json:"standardFuelCon,omitempty"`
	StaytimeParkingAddition []*StaytimeParkingAddition `protobuf:"bytes,44,rep,name=staytimeParkingAddition" json:"staytimeParkingAddition,omitempty"`
	EcuDate                 *int64                     `protobuf:"varint,45,opt,name=ecuDate" json:"ecuDate,omitempty"`
	TemperatureAddition     *TireTemperatureAddition   `protobuf:"bytes,46,opt,name=temperatureAddition" json:"temperatureAddition,omitempty"`
	CancleBreakdownAddition *VehicleBreakdownAddition  `protobuf:"bytes,47,opt,name=cancleBreakdownAddition" json:"cancleBreakdownAddition,omitempty"`
	TerminalId              *int64                     `protobuf:"varint,48,opt,name=terminalId" json:"terminalId,omitempty"`
	FactorySign             *int32                     `protobuf:"varint,49,opt,name=factorySign" json:"factorySign,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                   `json:"-"`
	XXX_unrecognized        []byte                     `json:"-"`
	XXX_sizecache           int32                      `json:"-"`
}

func (m *LocationData) Reset()         { *m = LocationData{} }
func (m *LocationData) String() string { return proto.CompactTextString(m) }
func (*LocationData) ProtoMessage()    {}
func (*LocationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_LocationData_ad819f23dcf63e85, []int{0}
}
func (m *LocationData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationData.Unmarshal(m, b)
}
func (m *LocationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationData.Marshal(b, m, deterministic)
}
func (dst *LocationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationData.Merge(dst, src)
}
func (m *LocationData) XXX_Size() int {
	return xxx_messageInfo_LocationData.Size(m)
}
func (m *LocationData) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationData.DiscardUnknown(m)
}

var xxx_messageInfo_LocationData proto.InternalMessageInfo

func (m *LocationData) GetAlarm() int64 {
	if m != nil && m.Alarm != nil {
		return *m.Alarm
	}
	return 0
}

func (m *LocationData) GetStatus() int64 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *LocationData) GetLongitude() int32 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

func (m *LocationData) GetLatitude() int32 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}

func (m *LocationData) GetOriginalLng() int32 {
	if m != nil && m.OriginalLng != nil {
		return *m.OriginalLng
	}
	return 0
}

func (m *LocationData) GetOriginalLat() int32 {
	if m != nil && m.OriginalLat != nil {
		return *m.OriginalLat
	}
	return 0
}

func (m *LocationData) GetHeight() int32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *LocationData) GetSpeed() int32 {
	if m != nil && m.Speed != nil {
		return *m.Speed
	}
	return 0
}

func (m *LocationData) GetDirection() int32 {
	if m != nil && m.Direction != nil {
		return *m.Direction
	}
	return 0
}

func (m *LocationData) GetGpsDate() int64 {
	if m != nil && m.GpsDate != nil {
		return *m.GpsDate
	}
	return 0
}

func (m *LocationData) GetMileage() int64 {
	if m != nil && m.Mileage != nil {
		return *m.Mileage
	}
	return 0
}

func (m *LocationData) GetReceiveDate() int64 {
	if m != nil && m.ReceiveDate != nil {
		return *m.ReceiveDate
	}
	return 0
}

func (m *LocationData) GetIsPatch() bool {
	if m != nil && m.IsPatch != nil {
		return *m.IsPatch
	}
	return false
}

func (m *LocationData) GetOil() int32 {
	if m != nil && m.Oil != nil {
		return *m.Oil
	}
	return 0
}

func (m *LocationData) GetRecorderSpeed() int32 {
	if m != nil && m.RecorderSpeed != nil {
		return *m.RecorderSpeed
	}
	return 0
}

func (m *LocationData) GetSpeedAddition() []*SpeedAddition {
	if m != nil {
		return m.SpeedAddition
	}
	return nil
}

func (m *LocationData) GetAreaAddition() []*AreaAddition {
	if m != nil {
		return m.AreaAddition
	}
	return nil
}

func (m *LocationData) GetRouteAddition() []*RouteAddition {
	if m != nil {
		return m.RouteAddition
	}
	return nil
}

func (m *LocationData) GetTemAlarm() []*TemAddition {
	if m != nil {
		return m.TemAlarm
	}
	return nil
}

func (m *LocationData) GetStarStatus() int32 {
	if m != nil && m.StarStatus != nil {
		return *m.StarStatus
	}
	return 0
}

func (m *LocationData) GetStarNumber() int32 {
	if m != nil && m.StarNumber != nil {
		return *m.StarNumber
	}
	return 0
}

func (m *LocationData) GetAlarmIdentify() []int32 {
	if m != nil {
		return m.AlarmIdentify
	}
	return nil
}

func (m *LocationData) GetSignalStatus() int32 {
	if m != nil && m.SignalStatus != nil {
		return *m.SignalStatus
	}
	return 0
}

func (m *LocationData) GetIoStatus() int32 {
	if m != nil && m.IoStatus != nil {
		return *m.IoStatus
	}
	return 0
}

func (m *LocationData) GetAnalogAD0() int32 {
	if m != nil && m.AnalogAD0 != nil {
		return *m.AnalogAD0
	}
	return 0
}

func (m *LocationData) GetAnalogAD1() int32 {
	if m != nil && m.AnalogAD1 != nil {
		return *m.AnalogAD1
	}
	return 0
}

func (m *LocationData) GetSignalStrength() int32 {
	if m != nil && m.SignalStrength != nil {
		return *m.SignalStrength
	}
	return 0
}

func (m *LocationData) GetSatelliteNumber() int32 {
	if m != nil && m.SatelliteNumber != nil {
		return *m.SatelliteNumber
	}
	return 0
}

func (m *LocationData) GetIsValid() bool {
	if m != nil && m.IsValid != nil {
		return *m.IsValid
	}
	return false
}

func (m *LocationData) GetDefenceAddition() []*KeyPointFenceAddition {
	if m != nil {
		return m.DefenceAddition
	}
	return nil
}

func (m *LocationData) GetParkingAddition() []*OvertimeParkingAddition {
	if m != nil {
		return m.ParkingAddition
	}
	return nil
}

func (m *LocationData) GetStatusAddition() *VehicleStatusAddition {
	if m != nil {
		return m.StatusAddition
	}
	return nil
}

func (m *LocationData) GetBreakdownAddition() *VehicleBreakdownAddition {
	if m != nil {
		return m.BreakdownAddition
	}
	return nil
}

func (m *LocationData) GetAdditionAlarm() []byte {
	if m != nil {
		return m.AdditionAlarm
	}
	return nil
}

func (m *LocationData) GetAnalysisData() *DrivingBehaviorAnalysis {
	if m != nil {
		return m.AnalysisData
	}
	return nil
}

func (m *LocationData) GetBatteryPower() int32 {
	if m != nil && m.BatteryPower != nil {
		return *m.BatteryPower
	}
	return 0
}

func (m *LocationData) GetModuleVoltages() []*ModuleVoltage {
	if m != nil {
		return m.ModuleVoltages
	}
	return nil
}

func (m *LocationData) GetElectricVehicle() int64 {
	if m != nil && m.ElectricVehicle != nil {
		return *m.ElectricVehicle
	}
	return 0
}

func (m *LocationData) GetBatteryInfo() *BatteryVehicleInfo {
	if m != nil {
		return m.BatteryInfo
	}
	return nil
}

func (m *LocationData) GetAlarmFilter() int64 {
	if m != nil && m.AlarmFilter != nil {
		return *m.AlarmFilter
	}
	return 0
}

func (m *LocationData) GetStandardMileage() float32 {
	if m != nil && m.StandardMileage != nil {
		return *m.StandardMileage
	}
	return 0
}

func (m *LocationData) GetStandardFuelCon() float32 {
	if m != nil && m.StandardFuelCon != nil {
		return *m.StandardFuelCon
	}
	return 0
}

func (m *LocationData) GetStaytimeParkingAddition() []*StaytimeParkingAddition {
	if m != nil {
		return m.StaytimeParkingAddition
	}
	return nil
}

func (m *LocationData) GetEcuDate() int64 {
	if m != nil && m.EcuDate != nil {
		return *m.EcuDate
	}
	return 0
}

func (m *LocationData) GetTemperatureAddition() *TireTemperatureAddition {
	if m != nil {
		return m.TemperatureAddition
	}
	return nil
}

func (m *LocationData) GetCancleBreakdownAddition() *VehicleBreakdownAddition {
	if m != nil {
		return m.CancleBreakdownAddition
	}
	return nil
}

func (m *LocationData) GetTerminalId() int64 {
	if m != nil && m.TerminalId != nil {
		return *m.TerminalId
	}
	return 0
}

func (m *LocationData) GetFactorySign() int32 {
	if m != nil && m.FactorySign != nil {
		return *m.FactorySign
	}
	return 0
}

type SpeedAddition struct {
	Types                *AreaType `protobuf:"varint,1,req,name=types,enum=proto_dic.AreaType" json:"types,omitempty"`
	AreaId               *int64    `protobuf:"varint,2,opt,name=areaId" json:"areaId,omitempty"`
	LineId               *int64    `protobuf:"varint,3,opt,name=lineId" json:"lineId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SpeedAddition) Reset()         { *m = SpeedAddition{} }
func (m *SpeedAddition) String() string { return proto.CompactTextString(m) }
func (*SpeedAddition) ProtoMessage()    {}
func (*SpeedAddition) Descriptor() ([]byte, []int) {
	return fileDescriptor_LocationData_ad819f23dcf63e85, []int{1}
}
func (m *SpeedAddition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpeedAddition.Unmarshal(m, b)
}
func (m *SpeedAddition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpeedAddition.Marshal(b, m, deterministic)
}
func (dst *SpeedAddition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpeedAddition.Merge(dst, src)
}
func (m *SpeedAddition) XXX_Size() int {
	return xxx_messageInfo_SpeedAddition.Size(m)
}
func (m *SpeedAddition) XXX_DiscardUnknown() {
	xxx_messageInfo_SpeedAddition.DiscardUnknown(m)
}

var xxx_messageInfo_SpeedAddition proto.InternalMessageInfo

func (m *SpeedAddition) GetTypes() AreaType {
	if m != nil && m.Types != nil {
		return *m.Types
	}
	return AreaType_noType
}

func (m *SpeedAddition) GetAreaId() int64 {
	if m != nil && m.AreaId != nil {
		return *m.AreaId
	}
	return 0
}

func (m *SpeedAddition) GetLineId() int64 {
	if m != nil && m.LineId != nil {
		return *m.LineId
	}
	return 0
}

type AreaAddition struct {
	AreaType             *AreaType `protobuf:"varint,1,req,name=areaType,enum=proto_dic.AreaType" json:"areaType,omitempty"`
	AreaId               *int64    `protobuf:"varint,2,req,name=areaId" json:"areaId,omitempty"`
	Direction            *bool     `protobuf:"varint,3,req,name=direction" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AreaAddition) Reset()         { *m = AreaAddition{} }
func (m *AreaAddition) String() string { return proto.CompactTextString(m) }
func (*AreaAddition) ProtoMessage()    {}
func (*AreaAddition) Descriptor() ([]byte, []int) {
	return fileDescriptor_LocationData_ad819f23dcf63e85, []int{2}
}
func (m *AreaAddition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaAddition.Unmarshal(m, b)
}
func (m *AreaAddition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaAddition.Marshal(b, m, deterministic)
}
func (dst *AreaAddition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaAddition.Merge(dst, src)
}
func (m *AreaAddition) XXX_Size() int {
	return xxx_messageInfo_AreaAddition.Size(m)
}
func (m *AreaAddition) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaAddition.DiscardUnknown(m)
}

var xxx_messageInfo_AreaAddition proto.InternalMessageInfo

func (m *AreaAddition) GetAreaType() AreaType {
	if m != nil && m.AreaType != nil {
		return *m.AreaType
	}
	return AreaType_noType
}

func (m *AreaAddition) GetAreaId() int64 {
	if m != nil && m.AreaId != nil {
		return *m.AreaId
	}
	return 0
}

func (m *AreaAddition) GetDirection() bool {
	if m != nil && m.Direction != nil {
		return *m.Direction
	}
	return false
}

type RouteAddition struct {
	AreaId               *int64   `protobuf:"varint,1,req,name=areaId" json:"areaId,omitempty"`
	LineId               *int64   `protobuf:"varint,2,opt,name=lineId" json:"lineId,omitempty"`
	RouteTime            *int32   `protobuf:"varint,3,req,name=routeTime" json:"routeTime,omitempty"`
	RouteResult          *bool    `protobuf:"varint,4,req,name=routeResult" json:"routeResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteAddition) Reset()         { *m = RouteAddition{} }
func (m *RouteAddition) String() string { return proto.CompactTextString(m) }
func (*RouteAddition) ProtoMessage()    {}
func (*RouteAddition) Descriptor() ([]byte, []int) {
	return fileDescriptor_LocationData_ad819f23dcf63e85, []int{3}
}
func (m *RouteAddition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteAddition.Unmarshal(m, b)
}
func (m *RouteAddition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteAddition.Marshal(b, m, deterministic)
}
func (dst *RouteAddition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteAddition.Merge(dst, src)
}
func (m *RouteAddition) XXX_Size() int {
	return xxx_messageInfo_RouteAddition.Size(m)
}
func (m *RouteAddition) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteAddition.DiscardUnknown(m)
}

var xxx_messageInfo_RouteAddition proto.InternalMessageInfo

func (m *RouteAddition) GetAreaId() int64 {
	if m != nil && m.AreaId != nil {
		return *m.AreaId
	}
	return 0
}

func (m *RouteAddition) GetLineId() int64 {
	if m != nil && m.LineId != nil {
		return *m.LineId
	}
	return 0
}

func (m *RouteAddition) GetRouteTime() int32 {
	if m != nil && m.RouteTime != nil {
		return *m.RouteTime
	}
	return 0
}

func (m *RouteAddition) GetRouteResult() bool {
	if m != nil && m.RouteResult != nil {
		return *m.RouteResult
	}
	return false
}

type TemAddition struct {
	ChannelId            *int32   `protobuf:"varint,1,req,name=channelId" json:"channelId,omitempty"`
	TemAlarm             *bool    `protobuf:"varint,2,req,name=temAlarm" json:"temAlarm,omitempty"`
	Temperature          *int32   `protobuf:"varint,3,opt,name=temperature" json:"temperature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemAddition) Reset()         { *m = TemAddition{} }
func (m *TemAddition) String() string { return proto.CompactTextString(m) }
func (*TemAddition) ProtoMessage()    {}
func (*TemAddition) Descriptor() ([]byte, []int) {
	return fileDescriptor_LocationData_ad819f23dcf63e85, []int{4}
}
func (m *TemAddition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemAddition.Unmarshal(m, b)
}
func (m *TemAddition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemAddition.Marshal(b, m, deterministic)
}
func (dst *TemAddition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemAddition.Merge(dst, src)
}
func (m *TemAddition) XXX_Size() int {
	return xxx_messageInfo_TemAddition.Size(m)
}
func (m *TemAddition) XXX_DiscardUnknown() {
	xxx_messageInfo_TemAddition.DiscardUnknown(m)
}

var xxx_messageInfo_TemAddition proto.InternalMessageInfo

func (m *TemAddition) GetChannelId() int32 {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return 0
}

func (m *TemAddition) GetTemAlarm() bool {
	if m != nil && m.TemAlarm != nil {
		return *m.TemAlarm
	}
	return false
}

func (m *TemAddition) GetTemperature() int32 {
	if m != nil && m.Temperature != nil {
		return *m.Temperature
	}
	return 0
}

type KeyPointFenceAddition struct {
	AreaType             *AreaType `protobuf:"varint,1,req,name=areaType,enum=proto_dic.AreaType" json:"areaType,omitempty"`
	AreaId               *int64    `protobuf:"varint,2,req,name=areaId" json:"areaId,omitempty"`
	FenceAlarm           *bool     `protobuf:"varint,3,req,name=fenceAlarm" json:"fenceAlarm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *KeyPointFenceAddition) Reset()         { *m = KeyPointFenceAddition{} }
func (m *KeyPointFenceAddition) String() string { return proto.CompactTextString(m) }
func (*KeyPointFenceAddition) ProtoMessage()    {}
func (*KeyPointFenceAddition) Descriptor() ([]byte, []int) {
	return fileDescriptor_LocationData_ad819f23dcf63e85, []int{5}
}
func (m *KeyPointFenceAddition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyPointFenceAddition.Unmarshal(m, b)
}
func (m *KeyPointFenceAddition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyPointFenceAddition.Marshal(b, m, deterministic)
}
func (dst *KeyPointFenceAddition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyPointFenceAddition.Merge(dst, src)
}
func (m *KeyPointFenceAddition) XXX_Size() int {
	return xxx_messageInfo_KeyPointFenceAddition.Size(m)
}
func (m *KeyPointFenceAddition) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyPointFenceAddition.DiscardUnknown(m)
}

var xxx_messageInfo_KeyPointFenceAddition proto.InternalMessageInfo

func (m *KeyPointFenceAddition) GetAreaType() AreaType {
	if m != nil && m.AreaType != nil {
		return *m.AreaType
	}
	return AreaType_noType
}

func (m *KeyPointFenceAddition) GetAreaId() int64 {
	if m != nil && m.AreaId != nil {
		return *m.AreaId
	}
	return 0
}

func (m *KeyPointFenceAddition) GetFenceAlarm() bool {
	if m != nil && m.FenceAlarm != nil {
		return *m.FenceAlarm
	}
	return false
}

type OvertimeParkingAddition struct {
	AreaType             *AreaType `protobuf:"varint,1,req,name=areaType,enum=proto_dic.AreaType" json:"areaType,omitempty"`
	AreaId               *int64    `protobuf:"varint,2,req,name=areaId" json:"areaId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OvertimeParkingAddition) Reset()         { *m = OvertimeParkingAddition{} }
func (m *OvertimeParkingAddition) String() string { return proto.CompactTextString(m) }
func (*OvertimeParkingAddition) ProtoMessage()    {}
func (*OvertimeParkingAddition) Descriptor() ([]byte, []int) {
	return fileDescriptor_LocationData_ad819f23dcf63e85, []int{6}
}
func (m *OvertimeParkingAddition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OvertimeParkingAddition.Unmarshal(m, b)
}
func (m *OvertimeParkingAddition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OvertimeParkingAddition.Marshal(b, m, deterministic)
}
func (dst *OvertimeParkingAddition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OvertimeParkingAddition.Merge(dst, src)
}
func (m *OvertimeParkingAddition) XXX_Size() int {
	return xxx_messageInfo_OvertimeParkingAddition.Size(m)
}
func (m *OvertimeParkingAddition) XXX_DiscardUnknown() {
	xxx_messageInfo_OvertimeParkingAddition.DiscardUnknown(m)
}

var xxx_messageInfo_OvertimeParkingAddition proto.InternalMessageInfo

func (m *OvertimeParkingAddition) GetAreaType() AreaType {
	if m != nil && m.AreaType != nil {
		return *m.AreaType
	}
	return AreaType_noType
}

func (m *OvertimeParkingAddition) GetAreaId() int64 {
	if m != nil && m.AreaId != nil {
		return *m.AreaId
	}
	return 0
}

type StaytimeParkingAddition struct {
	AreaType             *AreaType `protobuf:"varint,1,req,name=areaType,enum=proto_dic.AreaType" json:"areaType,omitempty"`
	AreaId               *int64    `protobuf:"varint,2,req,name=areaId" json:"areaId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *StaytimeParkingAddition) Reset()         { *m = StaytimeParkingAddition{} }
func (m *StaytimeParkingAddition) String() string { return proto.CompactTextString(m) }
func (*StaytimeParkingAddition) ProtoMessage()    {}
func (*StaytimeParkingAddition) Descriptor() ([]byte, []int) {
	return fileDescriptor_LocationData_ad819f23dcf63e85, []int{7}
}
func (m *StaytimeParkingAddition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaytimeParkingAddition.Unmarshal(m, b)
}
func (m *StaytimeParkingAddition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaytimeParkingAddition.Marshal(b, m, deterministic)
}
func (dst *StaytimeParkingAddition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaytimeParkingAddition.Merge(dst, src)
}
func (m *StaytimeParkingAddition) XXX_Size() int {
	return xxx_messageInfo_StaytimeParkingAddition.Size(m)
}
func (m *StaytimeParkingAddition) XXX_DiscardUnknown() {
	xxx_messageInfo_StaytimeParkingAddition.DiscardUnknown(m)
}

var xxx_messageInfo_StaytimeParkingAddition proto.InternalMessageInfo

func (m *StaytimeParkingAddition) GetAreaType() AreaType {
	if m != nil && m.AreaType != nil {
		return *m.AreaType
	}
	return AreaType_noType
}

func (m *StaytimeParkingAddition) GetAreaId() int64 {
	if m != nil && m.AreaId != nil {
		return *m.AreaId
	}
	return 0
}

type VehicleStatusAddition struct {
	Status               []*VehicleStatusData `protobuf:"bytes,1,rep,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VehicleStatusAddition) Reset()         { *m = VehicleStatusAddition{} }
func (m *VehicleStatusAddition) String() string { return proto.CompactTextString(m) }
func (*VehicleStatusAddition) ProtoMessage()    {}
func (*VehicleStatusAddition) Descriptor() ([]byte, []int) {
	return fileDescriptor_LocationData_ad819f23dcf63e85, []int{8}
}
func (m *VehicleStatusAddition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VehicleStatusAddition.Unmarshal(m, b)
}
func (m *VehicleStatusAddition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VehicleStatusAddition.Marshal(b, m, deterministic)
}
func (dst *VehicleStatusAddition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VehicleStatusAddition.Merge(dst, src)
}
func (m *VehicleStatusAddition) XXX_Size() int {
	return xxx_messageInfo_VehicleStatusAddition.Size(m)
}
func (m *VehicleStatusAddition) XXX_DiscardUnknown() {
	xxx_messageInfo_VehicleStatusAddition.DiscardUnknown(m)
}

var xxx_messageInfo_VehicleStatusAddition proto.InternalMessageInfo

func (m *VehicleStatusAddition) GetStatus() []*VehicleStatusData {
	if m != nil {
		return m.Status
	}
	return nil
}

type VehicleBreakdownAddition struct {
	Breakdown            []*VehicleBreakdown `protobuf:"bytes,1,rep,name=breakdown" json:"breakdown,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *VehicleBreakdownAddition) Reset()         { *m = VehicleBreakdownAddition{} }
func (m *VehicleBreakdownAddition) String() string { return proto.CompactTextString(m) }
func (*VehicleBreakdownAddition) ProtoMessage()    {}
func (*VehicleBreakdownAddition) Descriptor() ([]byte, []int) {
	return fileDescriptor_LocationData_ad819f23dcf63e85, []int{9}
}
func (m *VehicleBreakdownAddition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VehicleBreakdownAddition.Unmarshal(m, b)
}
func (m *VehicleBreakdownAddition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VehicleBreakdownAddition.Marshal(b, m, deterministic)
}
func (dst *VehicleBreakdownAddition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VehicleBreakdownAddition.Merge(dst, src)
}
func (m *VehicleBreakdownAddition) XXX_Size() int {
	return xxx_messageInfo_VehicleBreakdownAddition.Size(m)
}
func (m *VehicleBreakdownAddition) XXX_DiscardUnknown() {
	xxx_messageInfo_VehicleBreakdownAddition.DiscardUnknown(m)
}

var xxx_messageInfo_VehicleBreakdownAddition proto.InternalMessageInfo

func (m *VehicleBreakdownAddition) GetBreakdown() []*VehicleBreakdown {
	if m != nil {
		return m.Breakdown
	}
	return nil
}

type ModuleVoltage struct {
	ModuleNum            *int32   `protobuf:"varint,1,req,name=moduleNum" json:"moduleNum,omitempty"`
	Number               *int32   `protobuf:"varint,2,req,name=number" json:"number,omitempty"`
	Voltage              *float32 `protobuf:"fixed32,3,req,name=voltage" json:"voltage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleVoltage) Reset()         { *m = ModuleVoltage{} }
func (m *ModuleVoltage) String() string { return proto.CompactTextString(m) }
func (*ModuleVoltage) ProtoMessage()    {}
func (*ModuleVoltage) Descriptor() ([]byte, []int) {
	return fileDescriptor_LocationData_ad819f23dcf63e85, []int{10}
}
func (m *ModuleVoltage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleVoltage.Unmarshal(m, b)
}
func (m *ModuleVoltage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleVoltage.Marshal(b, m, deterministic)
}
func (dst *ModuleVoltage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleVoltage.Merge(dst, src)
}
func (m *ModuleVoltage) XXX_Size() int {
	return xxx_messageInfo_ModuleVoltage.Size(m)
}
func (m *ModuleVoltage) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleVoltage.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleVoltage proto.InternalMessageInfo

func (m *ModuleVoltage) GetModuleNum() int32 {
	if m != nil && m.ModuleNum != nil {
		return *m.ModuleNum
	}
	return 0
}

func (m *ModuleVoltage) GetNumber() int32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func (m *ModuleVoltage) GetVoltage() float32 {
	if m != nil && m.Voltage != nil {
		return *m.Voltage
	}
	return 0
}

type BatteryVehicleInfo struct {
	MotorTemperature     *int32   `protobuf:"varint,1,opt,name=motorTemperature" json:"motorTemperature,omitempty"`
	MotorControlTemp     *int32   `protobuf:"varint,2,opt,name=motorControlTemp" json:"motorControlTemp,omitempty"`
	McuFaultCode         *int32   `protobuf:"varint,3,opt,name=mcuFaultCode" json:"mcuFaultCode,omitempty"`
	BmsStatus            *int32   `protobuf:"varint,4,opt,name=bmsStatus" json:"bmsStatus,omitempty"`
	BatteryAveTem        *int32   `protobuf:"varint,5,opt,name=batteryAveTem" json:"batteryAveTem,omitempty"`
	BatteryCurrent       *float32 `protobuf:"fixed32,6,opt,name=batteryCurrent" json:"batteryCurrent,omitempty"`
	TotalBatteryV        *float32 `protobuf:"fixed32,7,opt,name=totalBatteryV" json:"totalBatteryV,omitempty"`
	BatteryFaultCode     *int32   `protobuf:"varint,8,opt,name=batteryFaultCode" json:"batteryFaultCode,omitempty"`
	BatteryMaxTem        *int32   `protobuf:"varint,9,opt,name=batteryMaxTem" json:"batteryMaxTem,omitempty"`
	BatteryMinTem        *int32   `protobuf:"varint,10,opt,name=batteryMinTem" json:"batteryMinTem,omitempty"`
	BatteryMinSoc        *int32   `protobuf:"varint,11,opt,name=batteryMinSoc" json:"batteryMinSoc,omitempty"`
	MaxChargingV         *float32 `protobuf:"fixed32,12,opt,name=maxChargingV" json:"maxChargingV,omitempty"`
	MaxChargingE         *float32 `protobuf:"fixed32,13,opt,name=maxChargingE" json:"maxChargingE,omitempty"`
	TotalStatus          *int32   `protobuf:"varint,14,opt,name=totalStatus" json:"totalStatus,omitempty"`
	VehicleSpeed         *float32 `protobuf:"fixed32,15,opt,name=vehicleSpeed" json:"vehicleSpeed,omitempty"`
	ShiftStatus          *int32   `protobuf:"varint,16,opt,name=shiftStatus" json:"shiftStatus,omitempty"`
	VcuFaultCode         *int32   `protobuf:"varint,17,opt,name=vcuFaultCode" json:"vcuFaultCode,omitempty"`
	EnduranceMileage     *int32   `protobuf:"varint,18,opt,name=enduranceMileage" json:"enduranceMileage,omitempty"`
	AcceleratorPedal     *float32 `protobuf:"fixed32,19,opt,name=acceleratorPedal" json:"acceleratorPedal,omitempty"`
	BrakePedal           *float32 `protobuf:"fixed32,20,opt,name=brakePedal" json:"brakePedal,omitempty"`
	ModelInfo            *int32   `protobuf:"varint,21,opt,name=modelInfo" json:"modelInfo,omitempty"`
	SwitchInfo           *int32   `protobuf:"varint,22,opt,name=switchInfo" json:"switchInfo,omitempty"`
	ElectricAttachment   *int32   `protobuf:"varint,23,opt,name=electricAttachment" json:"electricAttachment,omitempty"`
	MotorRpm             *int32   `protobuf:"varint,24,opt,name=motorRpm" json:"motorRpm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatteryVehicleInfo) Reset()         { *m = BatteryVehicleInfo{} }
func (m *BatteryVehicleInfo) String() string { return proto.CompactTextString(m) }
func (*BatteryVehicleInfo) ProtoMessage()    {}
func (*BatteryVehicleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_LocationData_ad819f23dcf63e85, []int{11}
}
func (m *BatteryVehicleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatteryVehicleInfo.Unmarshal(m, b)
}
func (m *BatteryVehicleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatteryVehicleInfo.Marshal(b, m, deterministic)
}
func (dst *BatteryVehicleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatteryVehicleInfo.Merge(dst, src)
}
func (m *BatteryVehicleInfo) XXX_Size() int {
	return xxx_messageInfo_BatteryVehicleInfo.Size(m)
}
func (m *BatteryVehicleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BatteryVehicleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BatteryVehicleInfo proto.InternalMessageInfo

func (m *BatteryVehicleInfo) GetMotorTemperature() int32 {
	if m != nil && m.MotorTemperature != nil {
		return *m.MotorTemperature
	}
	return 0
}

func (m *BatteryVehicleInfo) GetMotorControlTemp() int32 {
	if m != nil && m.MotorControlTemp != nil {
		return *m.MotorControlTemp
	}
	return 0
}

func (m *BatteryVehicleInfo) GetMcuFaultCode() int32 {
	if m != nil && m.McuFaultCode != nil {
		return *m.McuFaultCode
	}
	return 0
}

func (m *BatteryVehicleInfo) GetBmsStatus() int32 {
	if m != nil && m.BmsStatus != nil {
		return *m.BmsStatus
	}
	return 0
}

func (m *BatteryVehicleInfo) GetBatteryAveTem() int32 {
	if m != nil && m.BatteryAveTem != nil {
		return *m.BatteryAveTem
	}
	return 0
}

func (m *BatteryVehicleInfo) GetBatteryCurrent() float32 {
	if m != nil && m.BatteryCurrent != nil {
		return *m.BatteryCurrent
	}
	return 0
}

func (m *BatteryVehicleInfo) GetTotalBatteryV() float32 {
	if m != nil && m.TotalBatteryV != nil {
		return *m.TotalBatteryV
	}
	return 0
}

func (m *BatteryVehicleInfo) GetBatteryFaultCode() int32 {
	if m != nil && m.BatteryFaultCode != nil {
		return *m.BatteryFaultCode
	}
	return 0
}

func (m *BatteryVehicleInfo) GetBatteryMaxTem() int32 {
	if m != nil && m.BatteryMaxTem != nil {
		return *m.BatteryMaxTem
	}
	return 0
}

func (m *BatteryVehicleInfo) GetBatteryMinTem() int32 {
	if m != nil && m.BatteryMinTem != nil {
		return *m.BatteryMinTem
	}
	return 0
}

func (m *BatteryVehicleInfo) GetBatteryMinSoc() int32 {
	if m != nil && m.BatteryMinSoc != nil {
		return *m.BatteryMinSoc
	}
	return 0
}

func (m *BatteryVehicleInfo) GetMaxChargingV() float32 {
	if m != nil && m.MaxChargingV != nil {
		return *m.MaxChargingV
	}
	return 0
}

func (m *BatteryVehicleInfo) GetMaxChargingE() float32 {
	if m != nil && m.MaxChargingE != nil {
		return *m.MaxChargingE
	}
	return 0
}

func (m *BatteryVehicleInfo) GetTotalStatus() int32 {
	if m != nil && m.TotalStatus != nil {
		return *m.TotalStatus
	}
	return 0
}

func (m *BatteryVehicleInfo) GetVehicleSpeed() float32 {
	if m != nil && m.VehicleSpeed != nil {
		return *m.VehicleSpeed
	}
	return 0
}

func (m *BatteryVehicleInfo) GetShiftStatus() int32 {
	if m != nil && m.ShiftStatus != nil {
		return *m.ShiftStatus
	}
	return 0
}

func (m *BatteryVehicleInfo) GetVcuFaultCode() int32 {
	if m != nil && m.VcuFaultCode != nil {
		return *m.VcuFaultCode
	}
	return 0
}

func (m *BatteryVehicleInfo) GetEnduranceMileage() int32 {
	if m != nil && m.EnduranceMileage != nil {
		return *m.EnduranceMileage
	}
	return 0
}

func (m *BatteryVehicleInfo) GetAcceleratorPedal() float32 {
	if m != nil && m.AcceleratorPedal != nil {
		return *m.AcceleratorPedal
	}
	return 0
}

func (m *BatteryVehicleInfo) GetBrakePedal() float32 {
	if m != nil && m.BrakePedal != nil {
		return *m.BrakePedal
	}
	return 0
}

func (m *BatteryVehicleInfo) GetModelInfo() int32 {
	if m != nil && m.ModelInfo != nil {
		return *m.ModelInfo
	}
	return 0
}

func (m *BatteryVehicleInfo) GetSwitchInfo() int32 {
	if m != nil && m.SwitchInfo != nil {
		return *m.SwitchInfo
	}
	return 0
}

func (m *BatteryVehicleInfo) GetElectricAttachment() int32 {
	if m != nil && m.ElectricAttachment != nil {
		return *m.ElectricAttachment
	}
	return 0
}

func (m *BatteryVehicleInfo) GetMotorRpm() int32 {
	if m != nil && m.MotorRpm != nil {
		return *m.MotorRpm
	}
	return 0
}

func init() {
	proto.RegisterType((*LocationData)(nil), "proto_dic.LocationData")
	proto.RegisterType((*SpeedAddition)(nil), "proto_dic.SpeedAddition")
	proto.RegisterType((*AreaAddition)(nil), "proto_dic.AreaAddition")
	proto.RegisterType((*RouteAddition)(nil), "proto_dic.RouteAddition")
	proto.RegisterType((*TemAddition)(nil), "proto_dic.TemAddition")
	proto.RegisterType((*KeyPointFenceAddition)(nil), "proto_dic.KeyPointFenceAddition")
	proto.RegisterType((*OvertimeParkingAddition)(nil), "proto_dic.OvertimeParkingAddition")
	proto.RegisterType((*StaytimeParkingAddition)(nil), "proto_dic.StaytimeParkingAddition")
	proto.RegisterType((*VehicleStatusAddition)(nil), "proto_dic.VehicleStatusAddition")
	proto.RegisterType((*VehicleBreakdownAddition)(nil), "proto_dic.VehicleBreakdownAddition")
	proto.RegisterType((*ModuleVoltage)(nil), "proto_dic.ModuleVoltage")
	proto.RegisterType((*BatteryVehicleInfo)(nil), "proto_dic.BatteryVehicleInfo")
	proto.RegisterEnum("proto_dic.SignalStatus", SignalStatus_name, SignalStatus_value)
	proto.RegisterEnum("proto_dic.IoStauts", IoStauts_name, IoStauts_value)
}

func init() { proto.RegisterFile("LocationData.proto", fileDescriptor_LocationData_ad819f23dcf63e85) }

var fileDescriptor_LocationData_ad819f23dcf63e85 = []byte{
	// 1680 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5f, 0x73, 0xdb, 0xb8,
	0x11, 0x1f, 0xd1, 0xf1, 0x59, 0x86, 0x25, 0x9b, 0x41, 0x1c, 0x1b, 0xf5, 0x25, 0x29, 0xab, 0xbb,
	0x5e, 0x55, 0xb7, 0xf5, 0x5d, 0x32, 0x7d, 0xe9, 0x74, 0xa6, 0x8d, 0xe3, 0x9c, 0xa7, 0x6e, 0x93,
	0xab, 0x4b, 0xb9, 0xee, 0x4b, 0x3b, 0x37, 0x30, 0xb9, 0xa6, 0x50, 0x93, 0xa0, 0x06, 0x04, 0x9d,
	0xf3, 0x53, 0xf5, 0x01, 0xfa, 0xdc, 0xcf, 0xd4, 0x8f, 0xd5, 0x59, 0x00, 0xa4, 0x40, 0xc9, 0xce,
	0xf4, 0x21, 0x4f, 0xd2, 0xfe, 0xf6, 0xb7, 0x7f, 0x00, 0x2e, 0x76, 0x01, 0x42, 0xdf, 0x95, 0x09,
	0xd7, 0xa2, 0x94, 0x6f, 0xb9, 0xe6, 0x47, 0x33, 0x55, 0xea, 0x92, 0x6e, 0x9a, 0x9f, 0xef, 0x53,
	0x91, 0x1c, 0x6c, 0x1f, 0x2b, 0xe0, 0x17, 0x77, 0x33, 0xb0, 0xaa, 0x83, 0xfd, 0x4b, 0x98, 0x8a,
	0x24, 0x87, 0x89, 0xe6, 0xba, 0xae, 0x16, 0x36, 0x07, 0x7b, 0x4e, 0xf1, 0x46, 0x01, 0xbf, 0x49,
	0xcb, 0x0f, 0xd2, 0xe1, 0xcf, 0xdf, 0x2a, 0x71, 0x2b, 0x64, 0xf6, 0x06, 0xa6, 0xfc, 0x56, 0x94,
	0xea, 0x58, 0xf2, 0xfc, 0xae, 0x12, 0x55, 0xa3, 0xbe, 0x10, 0x0a, 0x2e, 0xa0, 0x98, 0x81, 0xe2,
	0xba, 0x56, 0x70, 0x9c, 0xa6, 0x02, 0xb3, 0xb1, 0xea, 0xd1, 0x7f, 0x43, 0x32, 0xf0, 0x13, 0xa4,
	0xbb, 0x64, 0x9d, 0xe7, 0x5c, 0x15, 0xac, 0x17, 0x05, 0xe3, 0xb5, 0xd8, 0x0a, 0x74, 0x8f, 0x7c,
	0x56, 0x99, 0x84, 0x58, 0x60, 0x60, 0x27, 0xd1, 0x67, 0x64, 0x33, 0x2f, 0x65, 0x26, 0x74, 0x9d,
	0x02, 0x5b, 0x8b, 0x7a, 0xe3, 0xf5, 0x78, 0x01, 0xd0, 0x03, 0xd2, 0xcf, 0xb9, 0xb6, 0xca, 0x47,
	0x46, 0xd9, 0xca, 0x34, 0x22, 0x5b, 0xa5, 0x12, 0x99, 0x90, 0x3c, 0x7f, 0x27, 0x33, 0xb6, 0x6e,
	0xd4, 0x3e, 0xd4, 0x61, 0x70, 0xcd, 0x3e, 0x5b, 0x62, 0x70, 0x8d, 0x59, 0x4d, 0x41, 0x64, 0x53,
	0xcd, 0x36, 0xa2, 0x60, 0xbc, 0x1e, 0x3b, 0x09, 0xd7, 0x50, 0xcd, 0x00, 0x52, 0xd6, 0x37, 0xb0,
	0x15, 0x30, 0xd7, 0x54, 0x28, 0x48, 0x70, 0xa9, 0x6c, 0xd3, 0x68, 0x16, 0x00, 0x65, 0x64, 0x23,
	0x9b, 0xe1, 0x7e, 0x03, 0x23, 0x66, 0x89, 0x8d, 0x88, 0x9a, 0x42, 0xe4, 0xc0, 0x33, 0x60, 0x5b,
	0x51, 0x0f, 0x35, 0x4e, 0xc4, 0x0c, 0x15, 0x24, 0x20, 0x6e, 0xc1, 0xd8, 0x0d, 0x8c, 0x9d, 0x0f,
	0xa1, 0xad, 0xa8, 0xce, 0xb9, 0x4e, 0xa6, 0x6c, 0x18, 0x05, 0xe3, 0x7e, 0xdc, 0x88, 0x34, 0x24,
	0x6b, 0xa5, 0xc8, 0xd9, 0xb6, 0x59, 0x15, 0xfe, 0xa5, 0x5f, 0x92, 0xa1, 0x82, 0xa4, 0x54, 0x29,
	0xa8, 0x89, 0xc9, 0x7e, 0xc7, 0xe8, 0xba, 0x20, 0xfd, 0x1d, 0x19, 0x9a, 0xe5, 0x34, 0xdf, 0x91,
	0x85, 0xd1, 0xda, 0x78, 0xeb, 0x15, 0x3b, 0x6a, 0x4b, 0xea, 0x68, 0xe2, 0xeb, 0xe3, 0x2e, 0x9d,
	0xfe, 0x96, 0x0c, 0xb8, 0x02, 0xde, 0x9a, 0x3f, 0x36, 0xe6, 0xfb, 0x9e, 0xf9, 0xb1, 0xa7, 0x8e,
	0x3b, 0x64, 0x0c, 0xae, 0xca, 0x5a, 0xb7, 0x45, 0xc4, 0xe8, 0x4a, 0xf0, 0xd8, 0xd7, 0xc7, 0x5d,
	0x3a, 0x7d, 0x45, 0xfa, 0x1a, 0x8a, 0x63, 0x53, 0x5f, 0x4f, 0x8c, 0xe9, 0x9e, 0x67, 0x7a, 0x01,
	0x45, 0x6b, 0xd8, 0xf2, 0xe8, 0x0b, 0x42, 0x2a, 0xcd, 0x95, 0x3d, 0x0f, 0x6c, 0xd7, 0xec, 0x89,
	0x87, 0x34, 0xfa, 0xef, 0xea, 0xe2, 0x0a, 0x14, 0x7b, 0xba, 0xd0, 0x5b, 0x04, 0xb7, 0xd5, 0xd4,
	0xf0, 0x59, 0x0a, 0x52, 0x8b, 0xeb, 0x3b, 0xb6, 0x17, 0xad, 0xe1, 0xb6, 0x76, 0x40, 0x3a, 0x22,
	0x83, 0x4a, 0x64, 0x92, 0xe7, 0x2e, 0xce, 0xbe, 0xf1, 0xd3, 0xc1, 0xb0, 0x9c, 0x45, 0xe9, 0xf4,
	0xcc, 0x96, 0x73, 0x23, 0x63, 0x71, 0x71, 0xc9, 0xf3, 0x32, 0x3b, 0x7e, 0xfb, 0x0d, 0xfb, 0x91,
	0x3d, 0x08, 0x2d, 0xe0, 0x6b, 0x5f, 0xb2, 0x83, 0xae, 0xf6, 0x25, 0xfd, 0x8a, 0x6c, 0x37, 0x71,
	0x14, 0xc8, 0x4c, 0x4f, 0xd9, 0xe7, 0x86, 0xb2, 0x84, 0xd2, 0x31, 0xd9, 0xa9, 0xb8, 0x86, 0x3c,
	0x17, 0x1a, 0xdc, 0x72, 0x9f, 0x19, 0xe2, 0x32, 0x6c, 0xcb, 0xee, 0x92, 0xe7, 0x22, 0x65, 0xcf,
	0xa3, 0x9e, 0x2d, 0x3b, 0x23, 0xd2, 0x3f, 0x92, 0x9d, 0x14, 0xae, 0x41, 0x26, 0x8b, 0x6f, 0xf8,
	0xc2, 0x7c, 0x88, 0xc8, 0xfb, 0x10, 0x7f, 0x82, 0xbb, 0xf3, 0x52, 0x48, 0x7d, 0xea, 0xf3, 0xe2,
	0x65, 0x43, 0xfa, 0x8e, 0xec, 0xcc, 0xb8, 0xba, 0x11, 0x32, 0x6b, 0x7d, 0xfd, 0xd8, 0xf8, 0x1a,
	0x79, 0xbe, 0xfe, 0x7c, 0x0b, 0x4a, 0x8b, 0x02, 0xce, 0xbb, 0xcc, 0x78, 0xd9, 0x94, 0xfe, 0x81,
	0x6c, 0xdb, 0xa6, 0xd2, 0x3a, 0x8b, 0xa2, 0xde, 0x52, 0x62, 0x9d, 0xde, 0xd8, 0xba, 0x5a, 0xb2,
	0xa3, 0x7f, 0x21, 0x8f, 0xaf, 0x9a, 0x26, 0xd9, 0x3a, 0xfb, 0x89, 0x71, 0xf6, 0xc5, 0xaa, 0xb3,
	0x37, 0xcb, 0xd4, 0x78, 0xd5, 0xda, 0x14, 0x91, 0xfb, 0x6f, 0xab, 0x77, 0x14, 0xf5, 0xc6, 0x83,
	0xb8, 0x0b, 0xd2, 0x53, 0x32, 0xe0, 0xae, 0xfb, 0x62, 0x2f, 0x65, 0x5f, 0x98, 0x98, 0xfe, 0x6e,
	0x3c, 0xd0, 0xab, 0xe3, 0x8e, 0x1d, 0x16, 0xe3, 0x15, 0xd7, 0x1a, 0xd4, 0xdd, 0x79, 0xf9, 0x01,
	0x14, 0xfb, 0xd2, 0x16, 0xa3, 0x8f, 0xd1, 0xd7, 0x64, 0xbb, 0x28, 0xd3, 0x3a, 0x87, 0xcb, 0x32,
	0xd7, 0x3c, 0x83, 0x8a, 0xfd, 0x74, 0xe5, 0x2c, 0xbe, 0xf7, 0x09, 0xf1, 0x12, 0x1f, 0xcb, 0x09,
	0x72, 0x48, 0xb4, 0x12, 0x89, 0xdb, 0x0a, 0xf6, 0x95, 0xe9, 0x6f, 0xcb, 0x30, 0xfd, 0x3d, 0xd9,
	0x72, 0xb1, 0xcf, 0xe4, 0x75, 0xc9, 0x7e, 0x66, 0x96, 0xf5, 0xdc, 0x0b, 0xf4, 0xc6, 0x6a, 0x1d,
	0x1f, 0x49, 0xb1, 0x6f, 0x81, 0x8d, 0xd2, 0x1c, 0xb7, 0x53, 0x91, 0x6b, 0x50, 0x6c, 0x6c, 0xc2,
	0xf8, 0x90, 0xa9, 0x6d, 0xcd, 0x65, 0xca, 0x55, 0xfa, 0xde, 0x35, 0xdb, 0xc3, 0xa8, 0x37, 0x0e,
	0xe2, 0x65, 0xd8, 0x67, 0x9e, 0xd6, 0x90, 0x9f, 0x94, 0x92, 0xfd, 0xa2, 0xcb, 0x74, 0x30, 0xfd,
	0x3b, 0xd9, 0xaf, 0x34, 0xbf, 0xbb, 0xa7, 0xfa, 0xd8, 0x2f, 0x57, 0xea, 0x74, 0x72, 0x3f, 0x33,
	0x7e, 0xc8, 0x05, 0x9e, 0x31, 0x48, 0x6a, 0xd3, 0xf8, 0x7f, 0x65, 0xc7, 0x82, 0x13, 0xe9, 0x05,
	0x79, 0xa2, 0x57, 0x07, 0x2e, 0x3b, 0x5a, 0xa9, 0x86, 0x07, 0x46, 0x73, 0x7c, 0x9f, 0x39, 0xfd,
	0x07, 0xd9, 0x4f, 0xb8, 0xbc, 0xaf, 0x60, 0xd9, 0xd7, 0xff, 0x7f, 0x6d, 0x3f, 0xe4, 0x03, 0xdb,
	0xa8, 0x06, 0x55, 0xe0, 0x68, 0x3d, 0x4b, 0xd9, 0x37, 0x66, 0x45, 0x1e, 0x82, 0x9f, 0xf0, 0x9a,
	0x27, 0xba, 0x54, 0x77, 0x13, 0x91, 0x49, 0xf6, 0xd2, 0x4e, 0x63, 0x0f, 0x1a, 0xfd, 0x93, 0x0c,
	0x3b, 0x93, 0x87, 0xfe, 0x9c, 0xac, 0xeb, 0xbb, 0x19, 0x54, 0xe6, 0x2a, 0xb1, 0xfd, 0xea, 0xc9,
	0xd2, 0x8c, 0xc1, 0x4b, 0x4f, 0x6c, 0x19, 0x38, 0xc9, 0x71, 0xd0, 0x9c, 0xa5, 0x2c, 0x30, 0x91,
	0x9d, 0x84, 0x78, 0x2e, 0x24, 0x9c, 0xa5, 0xe6, 0x72, 0xb1, 0x16, 0x3b, 0x69, 0x54, 0x93, 0x81,
	0x3f, 0xa6, 0xe8, 0xd7, 0xa4, 0xcf, 0x9d, 0xcb, 0x8f, 0x45, 0x6b, 0x49, 0x9d, 0x80, 0x81, 0x17,
	0xb0, 0x73, 0x49, 0x58, 0x33, 0x23, 0x7b, 0x01, 0x8c, 0xfe, 0x45, 0x86, 0x9d, 0xf9, 0xe6, 0xb9,
	0xe9, 0x75, 0xdc, 0x2c, 0xf2, 0x0e, 0xfc, 0xbc, 0xd1, 0xbd, 0x99, 0x88, 0x17, 0xa2, 0x00, 0xe3,
	0x7e, 0x3d, 0x5e, 0x00, 0xe6, 0x3e, 0x81, 0x42, 0x0c, 0x55, 0x9d, 0x6b, 0xf6, 0xc8, 0x84, 0xf7,
	0xa1, 0x91, 0x20, 0x5b, 0xde, 0x94, 0x44, 0x77, 0xc9, 0x94, 0x4b, 0x09, 0xb9, 0xcb, 0x60, 0x3d,
	0x5e, 0x00, 0x38, 0xaf, 0xda, 0x69, 0x1b, 0x18, 0x5f, 0x8b, 0xa9, 0x1a, 0x91, 0x2d, 0xaf, 0xc8,
	0xdc, 0xd5, 0xcd, 0x87, 0x46, 0xf3, 0x1e, 0x79, 0x7a, 0xef, 0x20, 0xf8, 0x74, 0x9b, 0xfd, 0x82,
	0x10, 0x3b, 0x51, 0x4c, 0x8a, 0x76, 0xb7, 0x3d, 0x64, 0x74, 0x45, 0xf6, 0x1f, 0x18, 0x1f, 0x9f,
	0x2c, 0x07, 0x8c, 0xf1, 0xc0, 0xd1, 0xff, 0x74, 0x31, 0xde, 0x93, 0xa7, 0xf7, 0x4e, 0x2e, 0xfa,
	0xeb, 0xf6, 0x5a, 0xdd, 0x33, 0x0d, 0xe9, 0xd9, 0x43, 0xb3, 0x0e, 0xc7, 0x42, 0x73, 0xe9, 0x1e,
	0xfd, 0x95, 0xb0, 0x87, 0xce, 0x37, 0xfd, 0x0d, 0xd9, 0x6c, 0xa7, 0x97, 0x73, 0xfa, 0xf9, 0x47,
	0xfa, 0x42, 0xbc, 0x60, 0x8f, 0xbe, 0x27, 0xc3, 0xce, 0xc0, 0xc0, 0xea, 0xb2, 0x23, 0xe3, 0xbb,
	0xba, 0x68, 0xaa, 0xab, 0x05, 0x70, 0xb1, 0xd2, 0x5e, 0x42, 0x02, 0x7b, 0xf9, 0x96, 0xed, 0xdd,
	0xe3, 0xd6, 0x3a, 0x30, 0x5f, 0x34, 0x88, 0x1b, 0x71, 0xf4, 0x9f, 0x0d, 0x42, 0x57, 0x27, 0x05,
	0x3d, 0x24, 0x61, 0x51, 0xea, 0x52, 0x79, 0x9d, 0x90, 0xf5, 0x4c, 0x3d, 0xae, 0xe0, 0x2d, 0xf7,
	0xa4, 0x94, 0x5a, 0x95, 0x39, 0xaa, 0xcc, 0x09, 0x6b, 0xb8, 0x1e, 0x8e, 0x53, 0xb4, 0x48, 0xea,
	0x53, 0x5e, 0xe7, 0xfa, 0xa4, 0x6c, 0x9f, 0x27, 0x1d, 0x0c, 0x97, 0x78, 0x55, 0x54, 0xee, 0x4e,
	0x67, 0x9f, 0x28, 0x0b, 0x00, 0xa7, 0xbe, 0x9b, 0x62, 0xc7, 0xb7, 0xd8, 0xa8, 0xdd, 0x2b, 0xa5,
	0x0b, 0xe2, 0xf5, 0xcd, 0x01, 0x27, 0xb5, 0x52, 0x20, 0xed, 0x53, 0x25, 0x88, 0x97, 0x50, 0xf4,
	0xa6, 0x4b, 0xcd, 0xf3, 0x66, 0x0b, 0xd8, 0x86, 0xa1, 0x75, 0x41, 0x5c, 0xa1, 0xb3, 0x5b, 0x64,
	0xde, 0xb7, 0x2b, 0x5c, 0xc6, 0xbd, 0xfc, 0xde, 0xf3, 0x1f, 0x30, 0xbf, 0xcd, 0x4e, 0x7e, 0x16,
	0xf4, 0x59, 0x42, 0x22, 0x8b, 0x74, 0x59, 0x06, 0xec, 0xb2, 0x26, 0x65, 0x62, 0xde, 0x3a, 0x1d,
	0xd6, 0xa4, 0x4c, 0xcc, 0x9e, 0xf2, 0x1f, 0x4e, 0xa6, 0x5c, 0x65, 0x42, 0x66, 0x97, 0x6c, 0x60,
	0x96, 0xd0, 0xc1, 0x96, 0x38, 0xdf, 0xb2, 0xe1, 0x0a, 0xe7, 0x5b, 0xd3, 0x7e, 0x70, 0xd9, 0x6e,
	0xe7, 0xb7, 0x5d, 0xfb, 0x59, 0x40, 0xe8, 0xe5, 0xd6, 0x9d, 0x80, 0xf6, 0x31, 0x14, 0xc4, 0x1d,
	0x0c, 0xbd, 0x54, 0x53, 0x71, 0xad, 0x9d, 0x97, 0xd0, 0x7a, 0xf1, 0x20, 0xe3, 0xc5, 0xaf, 0x81,
	0xc7, 0xb6, 0x06, 0x7c, 0x0c, 0x77, 0x1c, 0x64, 0x5a, 0x2b, 0x2e, 0x13, 0x68, 0xee, 0x1e, 0xd4,
	0xee, 0xf8, 0x32, 0x8e, 0x5c, 0x9e, 0x24, 0x90, 0x63, 0x3d, 0x96, 0xea, 0x1c, 0x52, 0x9e, 0xb3,
	0x27, 0x26, 0xb3, 0x15, 0x1c, 0xbb, 0xdb, 0x95, 0xe2, 0x37, 0x60, 0x59, 0xbb, 0x86, 0xe5, 0x21,
	0xee, 0x78, 0x41, 0x6e, 0xee, 0x54, 0xf6, 0xdd, 0xb2, 0x00, 0xcc, 0xb3, 0xe6, 0x83, 0xd0, 0xc9,
	0xd4, 0xa8, 0xf7, 0xdc, 0xb3, 0xa6, 0x45, 0xe8, 0x11, 0xa1, 0xcd, 0x35, 0xed, 0x58, 0x6b, 0x9e,
	0x4c, 0x0b, 0xac, 0x3c, 0xfb, 0x6c, 0xb9, 0x47, 0x83, 0xc3, 0xc0, 0x9c, 0x90, 0x78, 0x56, 0x34,
	0x8f, 0x97, 0x46, 0x3e, 0xfc, 0x77, 0x40, 0x06, 0x13, 0xff, 0xa5, 0x33, 0x24, 0x9b, 0x12, 0xb8,
	0x7a, 0x87, 0xaf, 0xe9, 0xb0, 0x47, 0x07, 0xa4, 0x7f, 0xdd, 0x48, 0x01, 0x7d, 0x4a, 0x1e, 0x2b,
	0xfc, 0x7b, 0x51, 0x2b, 0x29, 0x64, 0x66, 0xe1, 0x47, 0x74, 0x97, 0x84, 0x39, 0x5c, 0x77, 0xd1,
	0x3e, 0xdd, 0x22, 0x1b, 0xb8, 0x64, 0x21, 0xb3, 0x30, 0x44, 0x41, 0xc1, 0x2d, 0xa8, 0x0a, 0xc2,
	0xc8, 0x38, 0x2d, 0x1d, 0xef, 0x35, 0x0d, 0xc9, 0x56, 0xc1, 0xd5, 0x0d, 0xb8, 0x28, 0x73, 0x0c,
	0xba, 0x51, 0xcd, 0x80, 0xdf, 0x80, 0x0a, 0xe7, 0x01, 0xdd, 0x25, 0x3b, 0x5c, 0xe0, 0xf1, 0xb6,
	0x7d, 0x0e, 0xfd, 0xcd, 0x1f, 0x21, 0x47, 0x42, 0xad, 0x15, 0xcf, 0xc3, 0x79, 0x9f, 0x0e, 0x49,
	0x5f, 0x81, 0xe6, 0xf8, 0x56, 0x0e, 0xe7, 0x21, 0xdd, 0x21, 0x84, 0x5f, 0x55, 0x7f, 0x2b, 0x4d,
	0x53, 0x0f, 0xe7, 0x11, 0xa5, 0x64, 0x38, 0x05, 0xae, 0x41, 0xb5, 0xd8, 0x6b, 0x4a, 0xc9, 0x20,
	0xc9, 0x6b, 0x9d, 0x4c, 0xed, 0xca, 0xc3, 0xf9, 0xbc, 0x77, 0x78, 0x48, 0xfa, 0x67, 0xf8, 0xae,
	0xab, 0x75, 0x45, 0x43, 0x32, 0x48, 0x01, 0x66, 0x93, 0x1c, 0x60, 0x86, 0x26, 0x66, 0x33, 0xaa,
	0x46, 0x0a, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xd1, 0x9b, 0xef, 0xde, 0x11, 0x00, 0x00,
}
