// Code generated by protoc-gen-go. DO NOT EDIT.
// source: VehicleBreakdown.proto

package proto_dic

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VehicleBreakdown struct {
	BreakdownSPNValue    *int32   `protobuf:"varint,1,req,name=breakdownSPNValue" json:"breakdownSPNValue,omitempty"`
	BreakdownFMIValue    *int32   `protobuf:"varint,2,req,name=breakdownFMIValue" json:"breakdownFMIValue,omitempty"`
	SpnChangeMode        *int32   `protobuf:"varint,3,opt,name=spnChangeMode" json:"spnChangeMode,omitempty"`
	FaultsCount          *int32   `protobuf:"varint,4,opt,name=faultsCount" json:"faultsCount,omitempty"`
	FaultType            *int32   `protobuf:"varint,5,opt,name=faultType" json:"faultType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VehicleBreakdown) Reset()         { *m = VehicleBreakdown{} }
func (m *VehicleBreakdown) String() string { return proto.CompactTextString(m) }
func (*VehicleBreakdown) ProtoMessage()    {}
func (*VehicleBreakdown) Descriptor() ([]byte, []int) {
	return fileDescriptor_VehicleBreakdown_660079f091aa954f, []int{0}
}
func (m *VehicleBreakdown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VehicleBreakdown.Unmarshal(m, b)
}
func (m *VehicleBreakdown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VehicleBreakdown.Marshal(b, m, deterministic)
}
func (dst *VehicleBreakdown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VehicleBreakdown.Merge(dst, src)
}
func (m *VehicleBreakdown) XXX_Size() int {
	return xxx_messageInfo_VehicleBreakdown.Size(m)
}
func (m *VehicleBreakdown) XXX_DiscardUnknown() {
	xxx_messageInfo_VehicleBreakdown.DiscardUnknown(m)
}

var xxx_messageInfo_VehicleBreakdown proto.InternalMessageInfo

func (m *VehicleBreakdown) GetBreakdownSPNValue() int32 {
	if m != nil && m.BreakdownSPNValue != nil {
		return *m.BreakdownSPNValue
	}
	return 0
}

func (m *VehicleBreakdown) GetBreakdownFMIValue() int32 {
	if m != nil && m.BreakdownFMIValue != nil {
		return *m.BreakdownFMIValue
	}
	return 0
}

func (m *VehicleBreakdown) GetSpnChangeMode() int32 {
	if m != nil && m.SpnChangeMode != nil {
		return *m.SpnChangeMode
	}
	return 0
}

func (m *VehicleBreakdown) GetFaultsCount() int32 {
	if m != nil && m.FaultsCount != nil {
		return *m.FaultsCount
	}
	return 0
}

func (m *VehicleBreakdown) GetFaultType() int32 {
	if m != nil && m.FaultType != nil {
		return *m.FaultType
	}
	return 0
}

func init() {
	proto.RegisterType((*VehicleBreakdown)(nil), "proto_dic.VehicleBreakdown")
}

func init() {
	proto.RegisterFile("VehicleBreakdown.proto", fileDescriptor_VehicleBreakdown_660079f091aa954f)
}

var fileDescriptor_VehicleBreakdown_660079f091aa954f = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0b, 0x4b, 0xcd, 0xc8,
	0x4c, 0xce, 0x49, 0x75, 0x2a, 0x4a, 0x4d, 0xcc, 0x4e, 0xc9, 0x2f, 0xcf, 0xd3, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x04, 0x53, 0xf1, 0x29, 0x99, 0xc9, 0x4a, 0x57, 0x18, 0xb9, 0x04, 0xd0,
	0x55, 0x09, 0xe9, 0x70, 0x09, 0x26, 0xc1, 0x38, 0xc1, 0x01, 0x7e, 0x61, 0x89, 0x39, 0xa5, 0xa9,
	0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0xac, 0x41, 0x98, 0x12, 0x28, 0xaa, 0xdd, 0x7c, 0x3d, 0x21, 0xaa,
	0x99, 0xd0, 0x54, 0xc3, 0x24, 0x84, 0x54, 0xb8, 0x78, 0x8b, 0x0b, 0xf2, 0x9c, 0x33, 0x12, 0xf3,
	0xd2, 0x53, 0x7d, 0xf3, 0x53, 0x52, 0x25, 0x98, 0x15, 0x18, 0x35, 0x58, 0x83, 0x50, 0x05, 0x85,
	0x14, 0xb8, 0xb8, 0xd3, 0x12, 0x4b, 0x73, 0x4a, 0x8a, 0x9d, 0xf3, 0x4b, 0xf3, 0x4a, 0x24, 0x58,
	0xc0, 0x6a, 0x90, 0x85, 0x84, 0x64, 0xb8, 0x38, 0xc1, 0xdc, 0x90, 0xca, 0x82, 0x54, 0x09, 0x56,
	0xb0, 0x3c, 0x42, 0x00, 0x10, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x7f, 0x19, 0x71, 0xfa, 0x00, 0x00,
	0x00,
}
